services:
  - type: worker
    name: esic-telegram-bot
    runtime: python
    repo: .
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: BOT_TOKEN
        value: 8594466501:AAGf8OYkw8AS8xmHoqSgI_uvamBodJiNAGw
